# Editorial assistance for the R Journal
<!--
This is where the proposal should be outlined. 
-->

## The Problem
<!--
At a high-level address what your proposal is and how it will address the problem identified. Highlight any benefits to the R Community that follow from solving the problem. This should be your most compelling section.
-->

The R Journal is the open access, refereed, journal of the R project. This is a major outlet for articulating new work contributed to the R community, in the areas of statistical computing. With the growing popularity of R, the number of submissions to the R Journal has exploded, and alongside this the impact factor of the journal is steadily increasing. The editorial board is swamped with papers, and potential new members are reluctant to join because the workload is daunting. The entire journal, from review to production, is produced by the editorial board members. For the long term viability of the journal we need to find resources to fund a production assistants to copy edit, nag reviewers, help finalize editions, and update the software infrastructure to automate production. 

```{r echo=FALSE, message=FALSE, warning=FALSE, error=FALSE}
library(tidyverse)
RJ <- read_csv("RJournal.csv", skip=1)
JCGS <- read_csv("JCGS.csv", skip=1) %>% filter(Year > 2011)
d1 <- RJ %>% select(Year, `Journal Impact Factor`) %>%
  rename(RJournal = `Journal Impact Factor`)
d2 <- JCGS %>% select(Year, `Journal Impact Factor`) %>%
  rename(JCGS = `Journal Impact Factor`) %>% select(-Year)
d <- bind_cols(d1, d2) %>% 
  gather(journal, IF, -Year)
ggplot(d, aes(x=Year, y=IF, colour=journal)) + 
  geom_line() + ylab("Impact Factor") +
  scale_colour_brewer("", palette="Dark2") +
  theme(legend.position="bottom")
```

### Outline of current operations

The current procedures to bring an issue to the public domain is manually intensive:

* Authors submit their manuscripts through a form, such as at `http://rjournal.github.io/submissions.html`. Submissions must be properly produced following the instructions here `http://rjournal.github.io/share/author-guide.pdf`.
About 10% of submissions fail to properly follow these directions. Some of this number are clearly unsuitable (e.g., they are written in word and for the wrong audience), but many are suitable, but for some reason have not followed the instructions properly.
* By using a standard form for submissions, new submissions can be brought into the R Journal repository through a home-grown `rj` package feature. This mostly works, but when it doesn't there can be issues that take time, must be resolved by hand. (For example, if a submission isn't properly processed due to some unresolvable font, a submission can be accidentally brought into the repository multiple times. When this occurs, there is a chance that an omission can occur.) 
* A new submission is recognized with a form email. In this email we immediately ask the authors to send along a script file (if not done already) and add DOI entries.
* After the managing editor assigns a manuscript to the handling editor and before the article is accepted, it is not unusual for the review process to take longer than advertised. (Finding reviewers can sometimes be time consuming.)
* Once an article is accepted, it is to be put online. This involves some features of the `rj` package. There is a fussiness with bibtex entries that can make this task tedious.
* When an issue is compiled, there is the time consuming task of copy editing. The last issue ran to over 500 pages and the copy editing was shared by just 3 editorial board members. The time to copy edit stretched into 6+ weeks.
* The managing editor must solicit various NEWS pieces for the journal. 
* Finally, compiling the issue again uses features of the `rj` package. These are not as robust as they should be (something as simple as dashes in a title broke the script last time). Nor are they used frequently enough by the managing editor to be seen as easy.

### Developments of publication infrastructure

Today's common working environment for collaborative publications that could be utilized to modernize the R Journal's operations, include github, travis, netlify, Rmarkdown, and [radix](https://blog.rstudio.com/2018/09/19/radix-for-r-markdown/).

## The Plan
<!--
Go into more detail about the specifics of the project and it delivers against the problem.

Depending on project type the detail section should include:

 - [ ] Minimum Viable Product
 - [ ] Architecture
 - [ ] Assumptions
-->

Funds are requested to hire personnel to assist with the administration of, and infrastructure development for, the R Journal. 

### Administration

An administrative assistant would be employed to:

* help in identify the failing submissions prior the managing editor seeing them.
* manually import submitted files, using the current system.
* oversee automatic emails to submitting authors, check details of submissions. 
* communicate manuscript assignment and reminders from managing editor to associate editors.
* handle the accepted article typesetting with the `rj` package.
* copy edit the issue.
* coordinate news items for the journal.
* handle the final typesetting of the issue.

### Infrastructure

The infrastructure for the journal will be overhauled. Github, Travis CI, and Rmarkdown will be used to automate much of the work of current journal editors.  

- The current R Journal proof-reading checklist will be converted to  automatic checks. 
- Authors would be expected to submit articles through github pull requests. Travis CI can be used to reproduce their articles and check if the articles are properly formatted according to the journal guidelines. 
- If approved to be an open review system, reviewers will be able to post reviews publicly on github. I
- Netlify will be used to generate an HTML preview page of an article for reviewers to read the article more easily. 
- A new journal style template will be developed using Rmarkdown and particularly, [Radix](https://blog.rstudio.com/2018/09/19/radix-for-r-markdown/) to assist authors in preparing their papers, and more efficiently automate production.

The new infrastructure will make the life of editors and reviewers easier, and significantly enhance the reproducibility of articles in the R Journal. If all goes as planned, the R Journal will be the first journal in the area of statistical computing which turns reproducibility into an automatic standard.

A bonus of this new system is that the journal issues can be a part of a true
website, to incorporate interactive graphics in publications, whilst also maintaining PDF articles for printing. Readers will be able to
provide further comments after the papers are published, so that instead of being [relegated to the published graveyard, articles become immortal](
https://andrewgelman.com/2018/10/24/study-fails-replicate-continues-get-referenced-no-problems-communication-channels-blocked/).

Di and Yihui will work substantially on this, and will also employ a technical assistant to help. 

## The Team

- Di Cook, Econometrics and Business Statistics, Monash University
- Olivia Lau, Google, USA
- John Verzani, Mathematics, City University of New York
- Yihui Xie, RStudio

John Verzani is the current Editor-in-Chief. Olivia Lau is an Executive Editor, scheduled to take over as Editor-in-Chief in 2020. Di Cook will join the Executive Editorial board in 2019. Yihui Xie is a developer of the Rmarkdown suite of of R packages for publishing. 

## Project Milestones

- early-2019 Di and Yihui work on developing and testing new infrastructure 

- mid-2019 editorial associate begins assisting current editorial board manage and streamline the communication, assumes the manual operations of the journal, and begins testing of the new infrastructure on new submissions. 

- late-2019 transition to new infrastructure

- mid-2020 operations in full swing

## How Can The ISC Help

The R Journal provides a valuable service to the global open source community, and funding from the ISC can help to overhaul the operations, to make it a leader among open, academic publications. 

### Funding

We request $75,000 in funding over 18 months. All of the funds will be spent on personnel salary, to facilitate the change in operations. We aim to cover two support staff salaries for 20 hour per week for this period.

Longer term, the changes in operations, should greatly reduce the editorial assistant time needed. This we hope could be covered long term by the R Foundation. 

## Dissemination

All materials developed as part of the project will be available publicly (on github.com) with a creative commons share-alike license. 

 
